### ISSUE TITLE
When refreshing from the menu, loader doesn't appear

### ISSUE THREAD

**Issue by isuru88** [Raathigesh/Lazymine#102]
#### Steps to recreate
- Open Lazymine
- Wait for the loading screen to disappear
- Open Menu
- Select Refresh
##### Expected Result
- Application controls should be greyed out and the loading animation should be shown.
##### Actual Result
- Weekly Summary is Invisible
- Time Entries card is active
- Loader is not visible

![capture](https://cloud.githubusercontent.com/assets/3070411/9958057/60cbc2c6-5e23-11e5-82b3-574ed9b3e56f.PNG)

**Comment by chathuranga** [comment]
I think this issue is addressed by the recent updates. Works fine now.
