### ISSUE TITLE
Time Entries Card is overlapping the Pre-loader

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#103]
Try a "Refresh", and the dark background pre-loader seems to be working but the Time Entries Card seems to be appearing over the pre-loader.
![image](https://cloud.githubusercontent.com/assets/71325/10268489/c894e26e-6ad7-11e5-8ad1-1211e69dd31f.png)

**Comment by chathuranga** [comment]
someone else to close :)

**Comment by Raathigesh** [comment]
Working fine now!
