### ISSUE TITLE
 Show Tracker and Issue ID in the selected tasks and Search Result

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#11]

**Comment by AwadMaharoof** [comment]
@isuru88 @Raathigesh @yohangz @chathuranga : Currently search results are ordered as:
1. Project name
2. Issue subject

What if we switch this order? As its the subject that an user will look at first and not the project name

**Comment by chathuranga** [comment]
The reason we thought in this way is, when user looks at the results, he can easily decide to skip the tasks in the same project seen close by.

**Comment by isuru88** [comment]
But the problem is that when a new task is added to the list, it goes to the middle. Which is a bit confusing.

**Comment by AwadMaharoof** [comment]
@chathuranga , If I'm not mistaken a majority of the users would be assigned only to a single project, therefore I feel using the subject as the initial identifier would be more user friendly. Any thoughts?

**Comment by chathuranga** [comment]
OK this was sorted in thinking of future task grouping as well. Let's change it to the usable manner as you feel.

**Comment by AwadMaharoof** [comment]
Tracker and issue ID are not visible in search results. Order remains unchanged. Lets switch this in a future release based on user feedback.

Fixed with b85f64e0a05bbdfd750df1c6b95904418b5bc096
