### ISSUE TITLE
Deleting an item auto expands the next item below, if one exists

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#2]

**Comment by chathuranga** [comment]
Look like this is going to be challenging, and reason seems to be by design of React.
http://stackoverflow.com/questions/24415631/reactjs-syntheticevent-stoppropagation-only-works-with-react-events

https://github.com/facebook/react/pull/1696

**Comment by chathuranga** [comment]
Re-appearing in the desktop build only.

**Comment by isuru88** [comment]
Fixed in 0b0bdfe380ea92445ff8eb695d6c834bbfb9b09e
