### ISSUE TITLE
Update Shell icon (.exe icon)

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#25]

**Comment by isuru88** [comment]
Need a new icon from @AwadMaharoof @azmy145 or @dhammika97. Current icon doesn't look so good.

**Comment by AwadMaharoof** [comment]
how about 
1. http://www.flaticon.com/free-icon/halloween-black-cat_61637
2. A hand drawn(badly) cat like: http://www.thelogomix.com/files/imagecache/v3-logo-detail/mad-cat.jpg
3. http://logopond.com/logos/3412e9305690cae5a4773ba0499efc8b.png

**Comment by isuru88** [comment]
Completed in e6828614e2886b97453e27866faad885c198b22d
