### ISSUE TITLE
Clicking on logo on the title bar redirects user back to time entry page even after clicking "disconnect"

### ISSUE THREAD

**Issue by AwadMaharoof** [Raathigesh/Lazymine#29]
Steps
1. Enter track URL and API key and access time entry page
2. Click "disconnect" from menu
3. User is redirected to initial page
4. Click Lazymine logo on title bar
5. User is redirected back to time entry page

**Comment by isuru88** [comment]
Need to clear the credentials properly during Disconnect.

**Comment by Raathigesh** [comment]
Issue fixed.
