### ISSUE TITLE
Time entered tasks should be shown until user clears it

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#3]
When user enters time for particular tasks, those tasks should stay in the screen until user decided to clear a particular task or clear all the tasks.

**Comment by isuru88** [comment]
We might end up posting the same time twice.

**Comment by Raathigesh** [comment]
We should clear the previously entered time and just keep the task available. Would that be ok ?

**Comment by chathuranga** [comment]
Also note that it's possible to post time entries for non existing items, through this feature. It has to be handled.

**Comment by Raathigesh** [comment]
i will take this!

**Comment by yohangz** [comment]
Updated the store to support the mentioned feature.
