### ISSUE TITLE
Comments don't get saved in Redmine

### ISSUE THREAD

**Issue by isuru88** [Raathigesh/Lazymine#35]
#### Steps to recreate
- Login to Lazymine
- Select a task from Searchbox
- Add the task details ( Comment, Tracker, Hours )
- Click 'Update' 
- Verify data on Redmine server
##### Expected Result
- Comment, Activity and Hours should be present on the server
##### Actual Result
- Comment is not present

**Comment by Raathigesh** [comment]
Fixed
