### ISSUE TITLE
Reduce the Width of search result pane

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#42]

**Comment by chathuranga** [comment]
I guess size meaning the width, right @Raathigesh ?

**Comment by Raathigesh** [comment]
That's right. Width should be reduced. Edited!

**Comment by AwadMaharoof** [comment]
Fixed with f621cdfcbed30b19de18563a1b8fb660513e1c6f

**Comment by Raathigesh** [comment]
I think we should center the result pane.

**Comment by AwadMaharoof** [comment]
Fixed with 1574b0b76d7917833d144c0531542bd1d8126b86

**Comment by yohangz** [comment]
It will look good if we increase the width of search result to fit the active task width so there wont be any distractions behind the result set.

**Comment by AwadMaharoof** [comment]
I don't agree with this since equal widths will result in a confusion between the search results and task list,

Further the search results appear "above" the tasks. as they are dynamic. This is a physical behaviour which is visually achieved by placing the search result on top of the tasks.

**Comment by yohangz** [comment]
Just a suggestion. lets see others views aswell.

**Comment by yohangz** [comment]
![width](https://cloud.githubusercontent.com/assets/5279079/8019812/1f2166dc-0c7f-11e5-881b-a887d653d310.png)

In above image i have a search result and i cant see the highlighted text because subject is too long. why don't we use the width which is already available. + keep the UX

**Comment by chathuranga** [comment]
I think we need to reduce only by few pixels. Looks like we are loosing a lot of width currently.

**Comment by isuru88** [comment]
What if we left align the search result and increase the width up to the menu icon? Also, we could add a divider between the menu icon and search.

**Comment by AwadMaharoof** [comment]
Increased search result width with eaddaa8cc23f68163260f71fd233bdfddb5e3c46
