### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by yohangz** [Raathigesh/Lazymine#51]
![tooltip](https://cloud.githubusercontent.com/assets/5279079/8019140/a0eb1a8c-0c5c-11e5-9d50-550ee4d35008.png)

Add tool-tips to above shown

**Comment by AwadMaharoof** [comment]
Suggest title text for each pls @Raathigesh @isuru88 @yohangz @chathuranga

**Comment by AwadMaharoof** [comment]
Fixed with 586539ea74c4c66001a32109f9857e607725515f
