### ISSUE TITLE
Menu not aligned properly with search box

### ISSUE THREAD

**Issue by yohangz** [Raathigesh/Lazymine#52]
![align](https://cloud.githubusercontent.com/assets/5279079/8019153/1cb377a4-0c5d-11e5-8f8d-37964b63c603.png)

**Comment by AwadMaharoof** [comment]
feel free to fix the small ones. you dont have to assign every ui issue to me :laughing:

**Comment by yohangz** [comment]
ROFL

**Comment by AwadMaharoof** [comment]
fixed with 43ecce4213d1c816e621af164b2792c004863f36
