### ISSUE TITLE
Newly added tasks are not synced through the background sync

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#55]
Steps to recreate.
1. Open Lazymine and wait till data loads.
2. Create a New task in Redmine.
3. Wait for 15 mins(current sync time period).
4. Do a search on Lazymine to see whether we can find the new task.

Result -> Newly added tasks can't be seen
Expected-> Newly added tasks should be able to find through Lazymine search.

**Comment by yohangz** [comment]
Fixed with 6dbb2355e2a90a5f935ee415b15e848873c4e89f
