### ISSUE TITLE
Entered(but not saved on server side) task,comment,activity,hours should be persistent between Lazymine application restarts

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#61]

**Comment by Raathigesh** [comment]
An item which is ready to be updated will be saved to local store.

**Comment by yohangz** [comment]
Fixed with: baeb46cb759c9cd5446fe8b732a346c98a79a04b and 1a6f5f8dde02d0ac9a7cefad52bd3589770b9790
