### ISSUE TITLE
Change date to yesterday, Enter time, Close the App, Open Again, Date is still yesterday

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#65]
Issue reported by @dhammika97

**Comment by chathuranga** [comment]
Expected behavior is to reset the date to TODAY after UPDATE ?

**Comment by Raathigesh** [comment]
Yes that's also should be done. But what's odd here is that after closing and reopening also the date was preserved.

**Comment by yohangz** [comment]
Fixed with: baeb46cb759c9cd5446fe8b732a346c98a79a04b and 1a6f5f8dde02d0ac9a7cefad52bd3589770b9790

**Comment by isuru88** [comment]
Not reproducible as at 107493d4e82ba80097b7bf7257e205b02f57f63b. However, the date does not reset in the following instances,
- Application Closed to tray 
- Application Minimized
- Time Updated
- Items Cleared

Should we address these? If not we can close this.

**Comment by isuru88** [comment]
Not going to fix this yo!
