### ISSUE TITLE
Partial Updates on Custom Fields

### ISSUE THREAD

**Issue by isuru88** [Raathigesh/Lazymine#69]
#### Steps to recreate
- Login to Lazymine
- Select several tasks from Searchbox
- Add Comment, Activity and Hours for all of the tasks
- Add required Custom Field values to some of the tasks
- Click 'Update'
- Verify data on Redmine server
##### Expected Result
- Should not post any data to Redmine server.
##### Actual Result
- Posts data to the Redmine server for the tasks which has the required Custom Field data.

**Comment by yohangz** [comment]
Fixed
