### ISSUE TITLE
Added tasks should be saved to local storage and removed tasks should be removed from local storage.

### ISSUE THREAD

**Issue by Raathigesh** [Raathigesh/Lazymine#7]
No need to worry about saving only time updated tasks as currently implemented.  Since user already have searched and added it, he might enter time later.

**Comment by yohangz** [comment]
Fixed in a6b10fff835dd268849ef27c5b660cdcf5ad5967

**Comment by yohangz** [comment]
Fixed in a6b10fff835dd268849ef27c5b660cdcf5ad5967
