### ISSUE TITLE
Weekly summary view

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#75]
Users should be able to navigate to a weekly summary view, through the menu to see the entered times for the current week.
Example screen would be as below.
![image](https://cloud.githubusercontent.com/assets/71325/8415354/c2e1aafe-1ebb-11e5-8487-48886b5ed2d3.png)

**Comment by dimuthun** [comment]
Request to increase the priority of this feature.

**Comment by Raathigesh** [comment]
@dimuthun Done and we are working on this. Expect a release soon  :+1:

**Comment by dimuthun** [comment]
Cool

**Comment by chathuranga** [comment]
@Raathigesh I guess we can consider this done?

**Comment by Raathigesh** [comment]
@chathuranga  yes. Closing!
