### ISSUE TITLE
Task list width changes when about page is opened

### ISSUE THREAD

**Issue by AwadMaharoof** [Raathigesh/Lazymine#85]

**Comment by AwadMaharoof** [comment]
Observation: padding-right of 17px added to body element when modal dialog is opened.

**Comment by AwadMaharoof** [comment]
Fixed with ad6123bc072e99e92a083517e30676f4698c1cb4

Can someone please verify and close this issue?

**Comment by chathuranga** [comment]
Verified the fix.
