### ISSUE TITLE
Mac - The tray icon is duplicated when connected and disconnected

### ISSUE THREAD

**Issue by lasitha-petthawadu** [Raathigesh/Lazymine#87]
The tray icon in mac replicates multiple times each time a disconnect happens.
Version : OSX Yosmite 10.10.2

![screen shot 2015-07-16 at 9 42 38 am](https://cloud.githubusercontent.com/assets/3533222/8715432/95a89836-2b9f-11e5-9d61-b92c0b5ba9d7.png)

**Comment by chathuranga** [comment]
@yohangz s perspective was, with the Mac behavior we don't need to tray icon in Mac, just need to remove it for Mac build.

**Comment by Raathigesh** [comment]
Fixed with Mac Latest Build
