### ISSUE TITLE
Search results getting overlapped by Weekly Summary text

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#96]
Please see below.
![image](https://cloud.githubusercontent.com/assets/71325/9717845/a748c64c-5593-11e5-8606-4e2e20f6dce7.png)

**Comment by AwadMaharoof** [comment]
Fixed with 8662609350f9b9eae4ca0bc060b9259059654047

Someone please verify

**Comment by chathuranga** [comment]
looks good.
