### ISSUE TITLE
Improving styling on the Weekly summary details

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#97]
Below summary details would be nicer with styling.
![image](https://cloud.githubusercontent.com/assets/71325/9717892/3270bc2a-5594-11e5-904a-0930132942f7.png)

**Comment by AwadMaharoof** [comment]
Fixed with b9725b52e0f92ba72dafe694453fca109a0f8b0e

can someone please verify and close this issue?

**Comment by Raathigesh** [comment]
Looks Good!
