### ISSUE TITLE
Improve formating of data provided to Weekly View details

### ISSUE THREAD

**Issue by chathuranga** [Raathigesh/Lazymine#98]
![image](https://cloud.githubusercontent.com/assets/71325/9717932/a5c1f978-5594-11e5-9207-8a544f4d4bdc.png)
1. If the tasks are available under local cache, show the task name instead of ID.
2. Show Day of weeks rather than August 31.. ->

**Comment by chathuranga** [comment]
Almost done. We just have to check the scenarion when task is closed hence not available on client side. @yohangz can u check that scenario.

**Comment by Raathigesh** [comment]
Curretnly Id of the issue is shown.
